name: athlos
description: A Dart package for implementing multiplayer online games.
version: 0.0.5
homepage: "https://pub.dev/packages/athlos/"
repository: "https://github.com/RayLabz/athlos_dart"

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.7
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
